//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.1008
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllPayWebServiceTest.DevPaymentCenterTenpay {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TenpayTradeQueryPost", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TenpayTradeQueryPost : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long MerchantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long MerchantId {
            get {
                return this.MerchantIdField;
            }
            set {
                if ((this.MerchantIdField.Equals(value) != true)) {
                    this.MerchantIdField = value;
                    this.RaisePropertyChanged("MerchantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string XMLData {
            get {
                return this.XMLDataField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLDataField, value) != true)) {
                    this.XMLDataField = value;
                    this.RaisePropertyChanged("XMLData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DevPaymentCenterTenpay.TenpaySoap")]
    public interface TenpaySoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的項目名稱  tenpayTradeQuery 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TenpayQuery", ReplyAction="*")]
        AllPayWebServiceTest.DevPaymentCenterTenpay.TenpayQueryResponse TenpayQuery(AllPayWebServiceTest.DevPaymentCenterTenpay.TenpayQueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TenpayQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TenpayQuery", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.DevPaymentCenterTenpay.TenpayQueryRequestBody Body;
        
        public TenpayQueryRequest() {
        }
        
        public TenpayQueryRequest(AllPayWebServiceTest.DevPaymentCenterTenpay.TenpayQueryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TenpayQueryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AllPayWebServiceTest.DevPaymentCenterTenpay.TenpayTradeQueryPost tenpayTradeQuery;
        
        public TenpayQueryRequestBody() {
        }
        
        public TenpayQueryRequestBody(AllPayWebServiceTest.DevPaymentCenterTenpay.TenpayTradeQueryPost tenpayTradeQuery) {
            this.tenpayTradeQuery = tenpayTradeQuery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TenpayQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TenpayQueryResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.DevPaymentCenterTenpay.TenpayQueryResponseBody Body;
        
        public TenpayQueryResponse() {
        }
        
        public TenpayQueryResponse(AllPayWebServiceTest.DevPaymentCenterTenpay.TenpayQueryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TenpayQueryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TenpayQueryResult;
        
        public TenpayQueryResponseBody() {
        }
        
        public TenpayQueryResponseBody(string TenpayQueryResult) {
            this.TenpayQueryResult = TenpayQueryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TenpaySoapChannel : AllPayWebServiceTest.DevPaymentCenterTenpay.TenpaySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TenpaySoapClient : System.ServiceModel.ClientBase<AllPayWebServiceTest.DevPaymentCenterTenpay.TenpaySoap>, AllPayWebServiceTest.DevPaymentCenterTenpay.TenpaySoap {
        
        public TenpaySoapClient() {
        }
        
        public TenpaySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TenpaySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TenpaySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TenpaySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.DevPaymentCenterTenpay.TenpayQueryResponse AllPayWebServiceTest.DevPaymentCenterTenpay.TenpaySoap.TenpayQuery(AllPayWebServiceTest.DevPaymentCenterTenpay.TenpayQueryRequest request) {
            return base.Channel.TenpayQuery(request);
        }
        
        public string TenpayQuery(AllPayWebServiceTest.DevPaymentCenterTenpay.TenpayTradeQueryPost tenpayTradeQuery) {
            AllPayWebServiceTest.DevPaymentCenterTenpay.TenpayQueryRequest inValue = new AllPayWebServiceTest.DevPaymentCenterTenpay.TenpayQueryRequest();
            inValue.Body = new AllPayWebServiceTest.DevPaymentCenterTenpay.TenpayQueryRequestBody();
            inValue.Body.tenpayTradeQuery = tenpayTradeQuery;
            AllPayWebServiceTest.DevPaymentCenterTenpay.TenpayQueryResponse retVal = ((AllPayWebServiceTest.DevPaymentCenterTenpay.TenpaySoap)(this)).TenpayQuery(inValue);
            return retVal.Body.TenpayQueryResult;
        }
    }
}
