//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.296
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllPayWebServiceTest.DevPaymentCenterCVS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://PaymentCenter.AllPay.com.tw/", ConfigurationName="DevPaymentCenterCVS.CVSSoap")]
    public interface CVSSoap {
        
        // CODEGEN: 命名空間 http://PaymentCenter.AllPay.com.tw/ 的項目名稱  merchantTradeNo 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://PaymentCenter.AllPay.com.tw/CVSQuery", ReplyAction="*")]
        AllPayWebServiceTest.DevPaymentCenterCVS.CVSQueryResponse CVSQuery(AllPayWebServiceTest.DevPaymentCenterCVS.CVSQueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CVSQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CVSQuery", Namespace="http://PaymentCenter.AllPay.com.tw/", Order=0)]
        public AllPayWebServiceTest.DevPaymentCenterCVS.CVSQueryRequestBody Body;
        
        public CVSQueryRequest() {
        }
        
        public CVSQueryRequest(AllPayWebServiceTest.DevPaymentCenterCVS.CVSQueryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PaymentCenter.AllPay.com.tw/")]
    public partial class CVSQueryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long merchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string merchantTradeNo;
        
        public CVSQueryRequestBody() {
        }
        
        public CVSQueryRequestBody(long merchantID, string merchantTradeNo) {
            this.merchantID = merchantID;
            this.merchantTradeNo = merchantTradeNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CVSQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CVSQueryResponse", Namespace="http://PaymentCenter.AllPay.com.tw/", Order=0)]
        public AllPayWebServiceTest.DevPaymentCenterCVS.CVSQueryResponseBody Body;
        
        public CVSQueryResponse() {
        }
        
        public CVSQueryResponse(AllPayWebServiceTest.DevPaymentCenterCVS.CVSQueryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PaymentCenter.AllPay.com.tw/")]
    public partial class CVSQueryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CVSQueryResult;
        
        public CVSQueryResponseBody() {
        }
        
        public CVSQueryResponseBody(string CVSQueryResult) {
            this.CVSQueryResult = CVSQueryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CVSSoapChannel : AllPayWebServiceTest.DevPaymentCenterCVS.CVSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CVSSoapClient : System.ServiceModel.ClientBase<AllPayWebServiceTest.DevPaymentCenterCVS.CVSSoap>, AllPayWebServiceTest.DevPaymentCenterCVS.CVSSoap {
        
        public CVSSoapClient() {
        }
        
        public CVSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CVSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CVSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CVSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.DevPaymentCenterCVS.CVSQueryResponse AllPayWebServiceTest.DevPaymentCenterCVS.CVSSoap.CVSQuery(AllPayWebServiceTest.DevPaymentCenterCVS.CVSQueryRequest request) {
            return base.Channel.CVSQuery(request);
        }
        
        public string CVSQuery(long merchantID, string merchantTradeNo) {
            AllPayWebServiceTest.DevPaymentCenterCVS.CVSQueryRequest inValue = new AllPayWebServiceTest.DevPaymentCenterCVS.CVSQueryRequest();
            inValue.Body = new AllPayWebServiceTest.DevPaymentCenterCVS.CVSQueryRequestBody();
            inValue.Body.merchantID = merchantID;
            inValue.Body.merchantTradeNo = merchantTradeNo;
            AllPayWebServiceTest.DevPaymentCenterCVS.CVSQueryResponse retVal = ((AllPayWebServiceTest.DevPaymentCenterCVS.CVSSoap)(this)).CVSQuery(inValue);
            return retVal.Body.CVSQueryResult;
        }
    }
}
