//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18063
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllPayWebServiceTest.PostGate {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PostGate.PostGateSoap")]
    public interface PostGateSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的項目名稱  strURL 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FormPost", ReplyAction="*")]
        AllPayWebServiceTest.PostGate.FormPostResponse FormPost(AllPayWebServiceTest.PostGate.FormPostRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的項目名稱  requestUrl 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoRequest", ReplyAction="*")]
        AllPayWebServiceTest.PostGate.DoRequestResponse DoRequest(AllPayWebServiceTest.PostGate.DoRequestRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的項目名稱  d 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LineWarning", ReplyAction="*")]
        AllPayWebServiceTest.PostGate.LineWarningResponse LineWarning(AllPayWebServiceTest.PostGate.LineWarningRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FormPostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FormPost", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.PostGate.FormPostRequestBody Body;
        
        public FormPostRequest() {
        }
        
        public FormPostRequest(AllPayWebServiceTest.PostGate.FormPostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FormPostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strURL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPostData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strProxyIP;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int intPort;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int intCodePage;
        
        public FormPostRequestBody() {
        }
        
        public FormPostRequestBody(string strURL, string strPostData, string strProxyIP, int intPort, int intCodePage) {
            this.strURL = strURL;
            this.strPostData = strPostData;
            this.strProxyIP = strProxyIP;
            this.intPort = intPort;
            this.intCodePage = intCodePage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FormPostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FormPostResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.PostGate.FormPostResponseBody Body;
        
        public FormPostResponse() {
        }
        
        public FormPostResponse(AllPayWebServiceTest.PostGate.FormPostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FormPostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FormPostResult;
        
        public FormPostResponseBody() {
        }
        
        public FormPostResponseBody(string FormPostResult) {
            this.FormPostResult = FormPostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoRequest", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.PostGate.DoRequestRequestBody Body;
        
        public DoRequestRequest() {
        }
        
        public DoRequestRequest(AllPayWebServiceTest.PostGate.DoRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string postData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string contentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int TimeoutSeconds;
        
        public DoRequestRequestBody() {
        }
        
        public DoRequestRequestBody(string requestUrl, string postData, string contentType, int TimeoutSeconds) {
            this.requestUrl = requestUrl;
            this.postData = postData;
            this.contentType = contentType;
            this.TimeoutSeconds = TimeoutSeconds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.PostGate.DoRequestResponseBody Body;
        
        public DoRequestResponse() {
        }
        
        public DoRequestResponse(AllPayWebServiceTest.PostGate.DoRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DoRequestResult;
        
        public DoRequestResponseBody() {
        }
        
        public DoRequestResponseBody(string DoRequestResult) {
            this.DoRequestResult = DoRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LineWarningRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LineWarning", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.PostGate.LineWarningRequestBody Body;
        
        public LineWarningRequest() {
        }
        
        public LineWarningRequest(AllPayWebServiceTest.PostGate.LineWarningRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LineWarningRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string d;
        
        public LineWarningRequestBody() {
        }
        
        public LineWarningRequestBody(string d) {
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LineWarningResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LineWarningResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.PostGate.LineWarningResponseBody Body;
        
        public LineWarningResponse() {
        }
        
        public LineWarningResponse(AllPayWebServiceTest.PostGate.LineWarningResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LineWarningResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LineWarningResult;
        
        public LineWarningResponseBody() {
        }
        
        public LineWarningResponseBody(string LineWarningResult) {
            this.LineWarningResult = LineWarningResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PostGateSoapChannel : AllPayWebServiceTest.PostGate.PostGateSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostGateSoapClient : System.ServiceModel.ClientBase<AllPayWebServiceTest.PostGate.PostGateSoap>, AllPayWebServiceTest.PostGate.PostGateSoap {
        
        public PostGateSoapClient() {
        }
        
        public PostGateSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostGateSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostGateSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostGateSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.PostGate.FormPostResponse AllPayWebServiceTest.PostGate.PostGateSoap.FormPost(AllPayWebServiceTest.PostGate.FormPostRequest request) {
            return base.Channel.FormPost(request);
        }
        
        public string FormPost(string strURL, string strPostData, string strProxyIP, int intPort, int intCodePage) {
            AllPayWebServiceTest.PostGate.FormPostRequest inValue = new AllPayWebServiceTest.PostGate.FormPostRequest();
            inValue.Body = new AllPayWebServiceTest.PostGate.FormPostRequestBody();
            inValue.Body.strURL = strURL;
            inValue.Body.strPostData = strPostData;
            inValue.Body.strProxyIP = strProxyIP;
            inValue.Body.intPort = intPort;
            inValue.Body.intCodePage = intCodePage;
            AllPayWebServiceTest.PostGate.FormPostResponse retVal = ((AllPayWebServiceTest.PostGate.PostGateSoap)(this)).FormPost(inValue);
            return retVal.Body.FormPostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.PostGate.DoRequestResponse AllPayWebServiceTest.PostGate.PostGateSoap.DoRequest(AllPayWebServiceTest.PostGate.DoRequestRequest request) {
            return base.Channel.DoRequest(request);
        }
        
        public string DoRequest(string requestUrl, string postData, string contentType, int TimeoutSeconds) {
            AllPayWebServiceTest.PostGate.DoRequestRequest inValue = new AllPayWebServiceTest.PostGate.DoRequestRequest();
            inValue.Body = new AllPayWebServiceTest.PostGate.DoRequestRequestBody();
            inValue.Body.requestUrl = requestUrl;
            inValue.Body.postData = postData;
            inValue.Body.contentType = contentType;
            inValue.Body.TimeoutSeconds = TimeoutSeconds;
            AllPayWebServiceTest.PostGate.DoRequestResponse retVal = ((AllPayWebServiceTest.PostGate.PostGateSoap)(this)).DoRequest(inValue);
            return retVal.Body.DoRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.PostGate.LineWarningResponse AllPayWebServiceTest.PostGate.PostGateSoap.LineWarning(AllPayWebServiceTest.PostGate.LineWarningRequest request) {
            return base.Channel.LineWarning(request);
        }
        
        public string LineWarning(string d) {
            AllPayWebServiceTest.PostGate.LineWarningRequest inValue = new AllPayWebServiceTest.PostGate.LineWarningRequest();
            inValue.Body = new AllPayWebServiceTest.PostGate.LineWarningRequestBody();
            inValue.Body.d = d;
            AllPayWebServiceTest.PostGate.LineWarningResponse retVal = ((AllPayWebServiceTest.PostGate.PostGateSoap)(this)).LineWarning(inValue);
            return retVal.Body.LineWarningResult;
        }
    }
}
