//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllPayWebServiceTest.StageVirtualWs {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Payment.allpay.com.tw/", ConfigurationName="StageVirtualWs.VirtualSoap")]
    public interface VirtualSoap {
        
        // CODEGEN: 命名空間 http://Payment.allpay.com.tw/ 的元素名稱  MerchantID 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://Payment.allpay.com.tw/QueryTrade", ReplyAction="*")]
        AllPayWebServiceTest.StageVirtualWs.QueryTradeResponse QueryTrade(AllPayWebServiceTest.StageVirtualWs.QueryTradeRequest request);
        
        // CODEGEN: 命名空間 http://Payment.allpay.com.tw/ 的元素名稱  sno 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://Payment.allpay.com.tw/QueryBySerialNo", ReplyAction="*")]
        AllPayWebServiceTest.StageVirtualWs.QueryBySerialNoResponse QueryBySerialNo(AllPayWebServiceTest.StageVirtualWs.QueryBySerialNoRequest request);
        
        // CODEGEN: 命名空間 http://Payment.allpay.com.tw/ 的元素名稱  MerchantID 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://Payment.allpay.com.tw/Exchange", ReplyAction="*")]
        AllPayWebServiceTest.StageVirtualWs.ExchangeResponse Exchange(AllPayWebServiceTest.StageVirtualWs.ExchangeRequest request);
        
        // CODEGEN: 命名空間 http://Payment.allpay.com.tw/ 的元素名稱  MerchantID 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://Payment.allpay.com.tw/ChargeBack", ReplyAction="*")]
        AllPayWebServiceTest.StageVirtualWs.ChargeBackResponse ChargeBack(AllPayWebServiceTest.StageVirtualWs.ChargeBackRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryTradeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryTrade", Namespace="http://Payment.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.StageVirtualWs.QueryTradeRequestBody Body;
        
        public QueryTradeRequest() {
        }
        
        public QueryTradeRequest(AllPayWebServiceTest.StageVirtualWs.QueryTradeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Payment.allpay.com.tw/")]
    public partial class QueryTradeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MerchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string XMLData;
        
        public QueryTradeRequestBody() {
        }
        
        public QueryTradeRequestBody(string MerchantID, string XMLData) {
            this.MerchantID = MerchantID;
            this.XMLData = XMLData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryTradeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryTradeResponse", Namespace="http://Payment.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.StageVirtualWs.QueryTradeResponseBody Body;
        
        public QueryTradeResponse() {
        }
        
        public QueryTradeResponse(AllPayWebServiceTest.StageVirtualWs.QueryTradeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Payment.allpay.com.tw/")]
    public partial class QueryTradeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QueryTradeResult;
        
        public QueryTradeResponseBody() {
        }
        
        public QueryTradeResponseBody(string QueryTradeResult) {
            this.QueryTradeResult = QueryTradeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryBySerialNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryBySerialNo", Namespace="http://Payment.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.StageVirtualWs.QueryBySerialNoRequestBody Body;
        
        public QueryBySerialNoRequest() {
        }
        
        public QueryBySerialNoRequest(AllPayWebServiceTest.StageVirtualWs.QueryBySerialNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Payment.allpay.com.tw/")]
    public partial class QueryBySerialNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public QueryBySerialNoRequestBody() {
        }
        
        public QueryBySerialNoRequestBody(string sno, string pwd) {
            this.sno = sno;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryBySerialNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryBySerialNoResponse", Namespace="http://Payment.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.StageVirtualWs.QueryBySerialNoResponseBody Body;
        
        public QueryBySerialNoResponse() {
        }
        
        public QueryBySerialNoResponse(AllPayWebServiceTest.StageVirtualWs.QueryBySerialNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Payment.allpay.com.tw/")]
    public partial class QueryBySerialNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QueryBySerialNoResult;
        
        public QueryBySerialNoResponseBody() {
        }
        
        public QueryBySerialNoResponseBody(string QueryBySerialNoResult) {
            this.QueryBySerialNoResult = QueryBySerialNoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExchangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Exchange", Namespace="http://Payment.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.StageVirtualWs.ExchangeRequestBody Body;
        
        public ExchangeRequest() {
        }
        
        public ExchangeRequest(AllPayWebServiceTest.StageVirtualWs.ExchangeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Payment.allpay.com.tw/")]
    public partial class ExchangeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MerchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string XMLData;
        
        public ExchangeRequestBody() {
        }
        
        public ExchangeRequestBody(string MerchantID, string XMLData) {
            this.MerchantID = MerchantID;
            this.XMLData = XMLData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExchangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExchangeResponse", Namespace="http://Payment.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.StageVirtualWs.ExchangeResponseBody Body;
        
        public ExchangeResponse() {
        }
        
        public ExchangeResponse(AllPayWebServiceTest.StageVirtualWs.ExchangeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Payment.allpay.com.tw/")]
    public partial class ExchangeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExchangeResult;
        
        public ExchangeResponseBody() {
        }
        
        public ExchangeResponseBody(string ExchangeResult) {
            this.ExchangeResult = ExchangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChargeBackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChargeBack", Namespace="http://Payment.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.StageVirtualWs.ChargeBackRequestBody Body;
        
        public ChargeBackRequest() {
        }
        
        public ChargeBackRequest(AllPayWebServiceTest.StageVirtualWs.ChargeBackRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Payment.allpay.com.tw/")]
    public partial class ChargeBackRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MerchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string XMLData;
        
        public ChargeBackRequestBody() {
        }
        
        public ChargeBackRequestBody(string MerchantID, string XMLData) {
            this.MerchantID = MerchantID;
            this.XMLData = XMLData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChargeBackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChargeBackResponse", Namespace="http://Payment.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.StageVirtualWs.ChargeBackResponseBody Body;
        
        public ChargeBackResponse() {
        }
        
        public ChargeBackResponse(AllPayWebServiceTest.StageVirtualWs.ChargeBackResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Payment.allpay.com.tw/")]
    public partial class ChargeBackResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ChargeBackResult;
        
        public ChargeBackResponseBody() {
        }
        
        public ChargeBackResponseBody(string ChargeBackResult) {
            this.ChargeBackResult = ChargeBackResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VirtualSoapChannel : AllPayWebServiceTest.StageVirtualWs.VirtualSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VirtualSoapClient : System.ServiceModel.ClientBase<AllPayWebServiceTest.StageVirtualWs.VirtualSoap>, AllPayWebServiceTest.StageVirtualWs.VirtualSoap {
        
        public VirtualSoapClient() {
        }
        
        public VirtualSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VirtualSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VirtualSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VirtualSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.StageVirtualWs.QueryTradeResponse AllPayWebServiceTest.StageVirtualWs.VirtualSoap.QueryTrade(AllPayWebServiceTest.StageVirtualWs.QueryTradeRequest request) {
            return base.Channel.QueryTrade(request);
        }
        
        public string QueryTrade(string MerchantID, string XMLData) {
            AllPayWebServiceTest.StageVirtualWs.QueryTradeRequest inValue = new AllPayWebServiceTest.StageVirtualWs.QueryTradeRequest();
            inValue.Body = new AllPayWebServiceTest.StageVirtualWs.QueryTradeRequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.XMLData = XMLData;
            AllPayWebServiceTest.StageVirtualWs.QueryTradeResponse retVal = ((AllPayWebServiceTest.StageVirtualWs.VirtualSoap)(this)).QueryTrade(inValue);
            return retVal.Body.QueryTradeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.StageVirtualWs.QueryBySerialNoResponse AllPayWebServiceTest.StageVirtualWs.VirtualSoap.QueryBySerialNo(AllPayWebServiceTest.StageVirtualWs.QueryBySerialNoRequest request) {
            return base.Channel.QueryBySerialNo(request);
        }
        
        public string QueryBySerialNo(string sno, string pwd) {
            AllPayWebServiceTest.StageVirtualWs.QueryBySerialNoRequest inValue = new AllPayWebServiceTest.StageVirtualWs.QueryBySerialNoRequest();
            inValue.Body = new AllPayWebServiceTest.StageVirtualWs.QueryBySerialNoRequestBody();
            inValue.Body.sno = sno;
            inValue.Body.pwd = pwd;
            AllPayWebServiceTest.StageVirtualWs.QueryBySerialNoResponse retVal = ((AllPayWebServiceTest.StageVirtualWs.VirtualSoap)(this)).QueryBySerialNo(inValue);
            return retVal.Body.QueryBySerialNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.StageVirtualWs.ExchangeResponse AllPayWebServiceTest.StageVirtualWs.VirtualSoap.Exchange(AllPayWebServiceTest.StageVirtualWs.ExchangeRequest request) {
            return base.Channel.Exchange(request);
        }
        
        public string Exchange(string MerchantID, string XMLData) {
            AllPayWebServiceTest.StageVirtualWs.ExchangeRequest inValue = new AllPayWebServiceTest.StageVirtualWs.ExchangeRequest();
            inValue.Body = new AllPayWebServiceTest.StageVirtualWs.ExchangeRequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.XMLData = XMLData;
            AllPayWebServiceTest.StageVirtualWs.ExchangeResponse retVal = ((AllPayWebServiceTest.StageVirtualWs.VirtualSoap)(this)).Exchange(inValue);
            return retVal.Body.ExchangeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.StageVirtualWs.ChargeBackResponse AllPayWebServiceTest.StageVirtualWs.VirtualSoap.ChargeBack(AllPayWebServiceTest.StageVirtualWs.ChargeBackRequest request) {
            return base.Channel.ChargeBack(request);
        }
        
        public string ChargeBack(string MerchantID, string XMLData) {
            AllPayWebServiceTest.StageVirtualWs.ChargeBackRequest inValue = new AllPayWebServiceTest.StageVirtualWs.ChargeBackRequest();
            inValue.Body = new AllPayWebServiceTest.StageVirtualWs.ChargeBackRequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.XMLData = XMLData;
            AllPayWebServiceTest.StageVirtualWs.ChargeBackResponse retVal = ((AllPayWebServiceTest.StageVirtualWs.VirtualSoap)(this)).ChargeBack(inValue);
            return retVal.Body.ChargeBackResult;
        }
    }
}
