//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.296
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllPayWebServiceTest.ProdPaymentCenterCredit {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://PaymentCenter.AllPay.com.tw/", ConfigurationName="ProdPaymentCenterCredit.creditcardSoap")]
    public interface creditcardSoap {
        
        // CODEGEN: 命名空間 http://PaymentCenter.AllPay.com.tw/ 的項目名稱  xmlData 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://PaymentCenter.AllPay.com.tw/CreateTrade", ReplyAction="*")]
        AllPayWebServiceTest.ProdPaymentCenterCredit.CreateTradeResponse CreateTrade(AllPayWebServiceTest.ProdPaymentCenterCredit.CreateTradeRequest request);
        
        // CODEGEN: 命名空間 http://PaymentCenter.AllPay.com.tw/ 的項目名稱  xmlData 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://PaymentCenter.AllPay.com.tw/VerifyOrderByOtp", ReplyAction="*")]
        AllPayWebServiceTest.ProdPaymentCenterCredit.VerifyOrderByOtpResponse VerifyOrderByOtp(AllPayWebServiceTest.ProdPaymentCenterCredit.VerifyOrderByOtpRequest request);
        
        // CODEGEN: 命名空間 http://PaymentCenter.AllPay.com.tw/ 的項目名稱  xmlData 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://PaymentCenter.AllPay.com.tw/ResendOtp", ReplyAction="*")]
        AllPayWebServiceTest.ProdPaymentCenterCredit.ResendOtpResponse ResendOtp(AllPayWebServiceTest.ProdPaymentCenterCredit.ResendOtpRequest request);
        
        // CODEGEN: 命名空間 http://PaymentCenter.AllPay.com.tw/ 的項目名稱  merchantTradeNo 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://PaymentCenter.AllPay.com.tw/QueryTrade", ReplyAction="*")]
        AllPayWebServiceTest.ProdPaymentCenterCredit.QueryTradeResponse QueryTrade(AllPayWebServiceTest.ProdPaymentCenterCredit.QueryTradeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTradeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTrade", Namespace="http://PaymentCenter.AllPay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ProdPaymentCenterCredit.CreateTradeRequestBody Body;
        
        public CreateTradeRequest() {
        }
        
        public CreateTradeRequest(AllPayWebServiceTest.ProdPaymentCenterCredit.CreateTradeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PaymentCenter.AllPay.com.tw/")]
    public partial class CreateTradeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long merchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlData;
        
        public CreateTradeRequestBody() {
        }
        
        public CreateTradeRequestBody(long merchantID, string xmlData) {
            this.merchantID = merchantID;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTradeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTradeResponse", Namespace="http://PaymentCenter.AllPay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ProdPaymentCenterCredit.CreateTradeResponseBody Body;
        
        public CreateTradeResponse() {
        }
        
        public CreateTradeResponse(AllPayWebServiceTest.ProdPaymentCenterCredit.CreateTradeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PaymentCenter.AllPay.com.tw/")]
    public partial class CreateTradeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateTradeResult;
        
        public CreateTradeResponseBody() {
        }
        
        public CreateTradeResponseBody(string CreateTradeResult) {
            this.CreateTradeResult = CreateTradeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyOrderByOtpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyOrderByOtp", Namespace="http://PaymentCenter.AllPay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ProdPaymentCenterCredit.VerifyOrderByOtpRequestBody Body;
        
        public VerifyOrderByOtpRequest() {
        }
        
        public VerifyOrderByOtpRequest(AllPayWebServiceTest.ProdPaymentCenterCredit.VerifyOrderByOtpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PaymentCenter.AllPay.com.tw/")]
    public partial class VerifyOrderByOtpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long merchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlData;
        
        public VerifyOrderByOtpRequestBody() {
        }
        
        public VerifyOrderByOtpRequestBody(long merchantID, string xmlData) {
            this.merchantID = merchantID;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyOrderByOtpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyOrderByOtpResponse", Namespace="http://PaymentCenter.AllPay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ProdPaymentCenterCredit.VerifyOrderByOtpResponseBody Body;
        
        public VerifyOrderByOtpResponse() {
        }
        
        public VerifyOrderByOtpResponse(AllPayWebServiceTest.ProdPaymentCenterCredit.VerifyOrderByOtpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PaymentCenter.AllPay.com.tw/")]
    public partial class VerifyOrderByOtpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerifyOrderByOtpResult;
        
        public VerifyOrderByOtpResponseBody() {
        }
        
        public VerifyOrderByOtpResponseBody(string VerifyOrderByOtpResult) {
            this.VerifyOrderByOtpResult = VerifyOrderByOtpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResendOtpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResendOtp", Namespace="http://PaymentCenter.AllPay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ProdPaymentCenterCredit.ResendOtpRequestBody Body;
        
        public ResendOtpRequest() {
        }
        
        public ResendOtpRequest(AllPayWebServiceTest.ProdPaymentCenterCredit.ResendOtpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PaymentCenter.AllPay.com.tw/")]
    public partial class ResendOtpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long merchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlData;
        
        public ResendOtpRequestBody() {
        }
        
        public ResendOtpRequestBody(long merchantID, string xmlData) {
            this.merchantID = merchantID;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResendOtpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResendOtpResponse", Namespace="http://PaymentCenter.AllPay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ProdPaymentCenterCredit.ResendOtpResponseBody Body;
        
        public ResendOtpResponse() {
        }
        
        public ResendOtpResponse(AllPayWebServiceTest.ProdPaymentCenterCredit.ResendOtpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PaymentCenter.AllPay.com.tw/")]
    public partial class ResendOtpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResendOtpResult;
        
        public ResendOtpResponseBody() {
        }
        
        public ResendOtpResponseBody(string ResendOtpResult) {
            this.ResendOtpResult = ResendOtpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryTradeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryTrade", Namespace="http://PaymentCenter.AllPay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ProdPaymentCenterCredit.QueryTradeRequestBody Body;
        
        public QueryTradeRequest() {
        }
        
        public QueryTradeRequest(AllPayWebServiceTest.ProdPaymentCenterCredit.QueryTradeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PaymentCenter.AllPay.com.tw/")]
    public partial class QueryTradeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long merchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string merchantTradeNo;
        
        public QueryTradeRequestBody() {
        }
        
        public QueryTradeRequestBody(long merchantID, string merchantTradeNo) {
            this.merchantID = merchantID;
            this.merchantTradeNo = merchantTradeNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryTradeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryTradeResponse", Namespace="http://PaymentCenter.AllPay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ProdPaymentCenterCredit.QueryTradeResponseBody Body;
        
        public QueryTradeResponse() {
        }
        
        public QueryTradeResponse(AllPayWebServiceTest.ProdPaymentCenterCredit.QueryTradeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PaymentCenter.AllPay.com.tw/")]
    public partial class QueryTradeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QueryTradeResult;
        
        public QueryTradeResponseBody() {
        }
        
        public QueryTradeResponseBody(string QueryTradeResult) {
            this.QueryTradeResult = QueryTradeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface creditcardSoapChannel : AllPayWebServiceTest.ProdPaymentCenterCredit.creditcardSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class creditcardSoapClient : System.ServiceModel.ClientBase<AllPayWebServiceTest.ProdPaymentCenterCredit.creditcardSoap>, AllPayWebServiceTest.ProdPaymentCenterCredit.creditcardSoap {
        
        public creditcardSoapClient() {
        }
        
        public creditcardSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public creditcardSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public creditcardSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public creditcardSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.ProdPaymentCenterCredit.CreateTradeResponse AllPayWebServiceTest.ProdPaymentCenterCredit.creditcardSoap.CreateTrade(AllPayWebServiceTest.ProdPaymentCenterCredit.CreateTradeRequest request) {
            return base.Channel.CreateTrade(request);
        }
        
        public string CreateTrade(long merchantID, string xmlData) {
            AllPayWebServiceTest.ProdPaymentCenterCredit.CreateTradeRequest inValue = new AllPayWebServiceTest.ProdPaymentCenterCredit.CreateTradeRequest();
            inValue.Body = new AllPayWebServiceTest.ProdPaymentCenterCredit.CreateTradeRequestBody();
            inValue.Body.merchantID = merchantID;
            inValue.Body.xmlData = xmlData;
            AllPayWebServiceTest.ProdPaymentCenterCredit.CreateTradeResponse retVal = ((AllPayWebServiceTest.ProdPaymentCenterCredit.creditcardSoap)(this)).CreateTrade(inValue);
            return retVal.Body.CreateTradeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.ProdPaymentCenterCredit.VerifyOrderByOtpResponse AllPayWebServiceTest.ProdPaymentCenterCredit.creditcardSoap.VerifyOrderByOtp(AllPayWebServiceTest.ProdPaymentCenterCredit.VerifyOrderByOtpRequest request) {
            return base.Channel.VerifyOrderByOtp(request);
        }
        
        public string VerifyOrderByOtp(long merchantID, string xmlData) {
            AllPayWebServiceTest.ProdPaymentCenterCredit.VerifyOrderByOtpRequest inValue = new AllPayWebServiceTest.ProdPaymentCenterCredit.VerifyOrderByOtpRequest();
            inValue.Body = new AllPayWebServiceTest.ProdPaymentCenterCredit.VerifyOrderByOtpRequestBody();
            inValue.Body.merchantID = merchantID;
            inValue.Body.xmlData = xmlData;
            AllPayWebServiceTest.ProdPaymentCenterCredit.VerifyOrderByOtpResponse retVal = ((AllPayWebServiceTest.ProdPaymentCenterCredit.creditcardSoap)(this)).VerifyOrderByOtp(inValue);
            return retVal.Body.VerifyOrderByOtpResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.ProdPaymentCenterCredit.ResendOtpResponse AllPayWebServiceTest.ProdPaymentCenterCredit.creditcardSoap.ResendOtp(AllPayWebServiceTest.ProdPaymentCenterCredit.ResendOtpRequest request) {
            return base.Channel.ResendOtp(request);
        }
        
        public string ResendOtp(long merchantID, string xmlData) {
            AllPayWebServiceTest.ProdPaymentCenterCredit.ResendOtpRequest inValue = new AllPayWebServiceTest.ProdPaymentCenterCredit.ResendOtpRequest();
            inValue.Body = new AllPayWebServiceTest.ProdPaymentCenterCredit.ResendOtpRequestBody();
            inValue.Body.merchantID = merchantID;
            inValue.Body.xmlData = xmlData;
            AllPayWebServiceTest.ProdPaymentCenterCredit.ResendOtpResponse retVal = ((AllPayWebServiceTest.ProdPaymentCenterCredit.creditcardSoap)(this)).ResendOtp(inValue);
            return retVal.Body.ResendOtpResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.ProdPaymentCenterCredit.QueryTradeResponse AllPayWebServiceTest.ProdPaymentCenterCredit.creditcardSoap.QueryTrade(AllPayWebServiceTest.ProdPaymentCenterCredit.QueryTradeRequest request) {
            return base.Channel.QueryTrade(request);
        }
        
        public string QueryTrade(long merchantID, string merchantTradeNo) {
            AllPayWebServiceTest.ProdPaymentCenterCredit.QueryTradeRequest inValue = new AllPayWebServiceTest.ProdPaymentCenterCredit.QueryTradeRequest();
            inValue.Body = new AllPayWebServiceTest.ProdPaymentCenterCredit.QueryTradeRequestBody();
            inValue.Body.merchantID = merchantID;
            inValue.Body.merchantTradeNo = merchantTradeNo;
            AllPayWebServiceTest.ProdPaymentCenterCredit.QueryTradeResponse retVal = ((AllPayWebServiceTest.ProdPaymentCenterCredit.creditcardSoap)(this)).QueryTrade(inValue);
            return retVal.Body.QueryTradeResult;
        }
    }
}
