//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllPayWebServiceTest.AllPaysharedws {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiReturnModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ApiReturnModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RtnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RtnMsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RtnCode {
            get {
                return this.RtnCodeField;
            }
            set {
                if ((this.RtnCodeField.Equals(value) != true)) {
                    this.RtnCodeField = value;
                    this.RaisePropertyChanged("RtnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RtnMsg {
            get {
                return this.RtnMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.RtnMsgField, value) != true)) {
                    this.RtnMsgField = value;
                    this.RaisePropertyChanged("RtnMsg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AllPaysharedws.AllPaySharedWSSoap")]
    public interface AllPaySharedWSSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  Phone 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        AllPayWebServiceTest.AllPaysharedws.SendSMSResponse SendSMS(AllPayWebServiceTest.AllPaysharedws.SendSMSRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  tradeNo 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddFastMember", ReplyAction="*")]
        AllPayWebServiceTest.AllPaysharedws.AddFastMemberResponse AddFastMember(AllPayWebServiceTest.AllPaysharedws.AddFastMemberRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  cName 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBonusMember", ReplyAction="*")]
        AllPayWebServiceTest.AllPaysharedws.AddBonusMemberResponse AddBonusMember(AllPayWebServiceTest.AllPaysharedws.AddBonusMemberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUnreadNotifyMessageCount", ReplyAction="*")]
        int GetUnreadNotifyMessageCount(long mid, int webSiteID);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  corpname 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewPersonalSeller", ReplyAction="*")]
        AllPayWebServiceTest.AllPaysharedws.AddNewPersonalSellerResponse AddNewPersonalSeller(AllPayWebServiceTest.AllPaysharedws.AddNewPersonalSellerRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  corpname 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewCompanySeller", ReplyAction="*")]
        AllPayWebServiceTest.AllPaysharedws.AddNewCompanySellerResponse AddNewCompanySeller(AllPayWebServiceTest.AllPaysharedws.AddNewCompanySellerRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  corpname 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewMerchant", ReplyAction="*")]
        AllPayWebServiceTest.AllPaysharedws.AddNewMerchantResponse AddNewMerchant(AllPayWebServiceTest.AllPaysharedws.AddNewMerchantRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  corpname 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateNewMerchant", ReplyAction="*")]
        AllPayWebServiceTest.AllPaysharedws.UpdateNewMerchantResponse UpdateNewMerchant(AllPayWebServiceTest.AllPaysharedws.UpdateNewMerchantRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  AddNewCompanyMerchantResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewCompanyMerchant", ReplyAction="*")]
        AllPayWebServiceTest.AllPaysharedws.AddNewCompanyMerchantResponse AddNewCompanyMerchant(AllPayWebServiceTest.AllPaysharedws.AddNewCompanyMerchantRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  subject 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNotifyMessage", ReplyAction="*")]
        AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageResponse AddNotifyMessage(AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  subject 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNotifyMessageAndPushRssByCustom", ReplyAction="*")]
        AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageAndPushRssByCustomResponse AddNotifyMessageAndPushRssByCustom(AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageAndPushRssByCustomRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  corpname 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewMerchantForRentDevice", ReplyAction="*")]
        AllPayWebServiceTest.AllPaysharedws.AddNewMerchantForRentDeviceResponse AddNewMerchantForRentDevice(AllPayWebServiceTest.AllPaysharedws.AddNewMerchantForRentDeviceRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  sKey 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AES_EnCrypt", ReplyAction="*")]
        AllPayWebServiceTest.AllPaysharedws.AES_EnCryptResponse AES_EnCrypt(AllPayWebServiceTest.AllPaysharedws.AES_EnCryptRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  sKey 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AES_DeCrypt", ReplyAction="*")]
        AllPayWebServiceTest.AllPaysharedws.AES_DeCryptResponse AES_DeCrypt(AllPayWebServiceTest.AllPaysharedws.AES_DeCryptRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(AllPayWebServiceTest.AllPaysharedws.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MsgData;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int SmsType;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(string Phone, string MsgData, int SmsType) {
            this.Phone = Phone;
            this.MsgData = MsgData;
            this.SmsType = SmsType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(AllPayWebServiceTest.AllPaysharedws.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSResult;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(string SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFastMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFastMember", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddFastMemberRequestBody Body;
        
        public AddFastMemberRequest() {
        }
        
        public AddFastMemberRequest(AllPayWebServiceTest.AllPaysharedws.AddFastMemberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddFastMemberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long tradeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tradeNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cellPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int addMember;
        
        public AddFastMemberRequestBody() {
        }
        
        public AddFastMemberRequestBody(long tradeID, string tradeNo, string cName, string cellPhone, string email, int addMember) {
            this.tradeID = tradeID;
            this.tradeNo = tradeNo;
            this.cName = cName;
            this.cellPhone = cellPhone;
            this.email = email;
            this.addMember = addMember;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFastMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFastMemberResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddFastMemberResponseBody Body;
        
        public AddFastMemberResponse() {
        }
        
        public AddFastMemberResponse(AllPayWebServiceTest.AllPaysharedws.AddFastMemberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddFastMemberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long AddFastMemberResult;
        
        public AddFastMemberResponseBody() {
        }
        
        public AddFastMemberResponseBody(long AddFastMemberResult) {
            this.AddFastMemberResult = AddFastMemberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBonusMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBonusMember", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddBonusMemberRequestBody Body;
        
        public AddBonusMemberRequest() {
        }
        
        public AddBonusMemberRequest(AllPayWebServiceTest.AllPaysharedws.AddBonusMemberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBonusMemberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IDNO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cellPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CompanyID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Birthday;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CompanyName;
        
        public AddBonusMemberRequestBody() {
        }
        
        public AddBonusMemberRequestBody(string cName, string IDNO, string cellPhone, string email, string CompanyID, string Birthday, string CompanyName) {
            this.cName = cName;
            this.IDNO = IDNO;
            this.cellPhone = cellPhone;
            this.email = email;
            this.CompanyID = CompanyID;
            this.Birthday = Birthday;
            this.CompanyName = CompanyName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBonusMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBonusMemberResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddBonusMemberResponseBody Body;
        
        public AddBonusMemberResponse() {
        }
        
        public AddBonusMemberResponse(AllPayWebServiceTest.AllPaysharedws.AddBonusMemberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBonusMemberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.ApiReturnModel AddBonusMemberResult;
        
        public AddBonusMemberResponseBody() {
        }
        
        public AddBonusMemberResponseBody(AllPayWebServiceTest.AllPaysharedws.ApiReturnModel AddBonusMemberResult) {
            this.AddBonusMemberResult = AddBonusMemberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewPersonalSellerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewPersonalSeller", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddNewPersonalSellerRequestBody Body;
        
        public AddNewPersonalSellerRequest() {
        }
        
        public AddNewPersonalSellerRequest(AllPayWebServiceTest.AllPaysharedws.AddNewPersonalSellerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewPersonalSellerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int otp_esc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long allpayMID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string corpname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string comboss;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string bossid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string webname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string contact;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string tel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string mobile;
        
        public AddNewPersonalSellerRequestBody() {
        }
        
        public AddNewPersonalSellerRequestBody(int otp_esc, long allpayMID, string corpname, string comboss, string bossid, string webname, string contact, string address, string tel, string mobile) {
            this.otp_esc = otp_esc;
            this.allpayMID = allpayMID;
            this.corpname = corpname;
            this.comboss = comboss;
            this.bossid = bossid;
            this.webname = webname;
            this.contact = contact;
            this.address = address;
            this.tel = tel;
            this.mobile = mobile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewPersonalSellerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewPersonalSellerResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddNewPersonalSellerResponseBody Body;
        
        public AddNewPersonalSellerResponse() {
        }
        
        public AddNewPersonalSellerResponse(AllPayWebServiceTest.AllPaysharedws.AddNewPersonalSellerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewPersonalSellerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddNewPersonalSellerResult;
        
        public AddNewPersonalSellerResponseBody() {
        }
        
        public AddNewPersonalSellerResponseBody(string AddNewPersonalSellerResult) {
            this.AddNewPersonalSellerResult = AddNewPersonalSellerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewCompanySellerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewCompanySeller", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddNewCompanySellerRequestBody Body;
        
        public AddNewCompanySellerRequest() {
        }
        
        public AddNewCompanySellerRequest(AllPayWebServiceTest.AllPaysharedws.AddNewCompanySellerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewCompanySellerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int otp_esc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long allpayMID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string corpname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string corpid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string comboss;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string bossid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string webname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string contact;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string tel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string mobile;
        
        public AddNewCompanySellerRequestBody() {
        }
        
        public AddNewCompanySellerRequestBody(int otp_esc, long allpayMID, string corpname, string corpid, string comboss, string bossid, string webname, string contact, string address, string tel, string mobile) {
            this.otp_esc = otp_esc;
            this.allpayMID = allpayMID;
            this.corpname = corpname;
            this.corpid = corpid;
            this.comboss = comboss;
            this.bossid = bossid;
            this.webname = webname;
            this.contact = contact;
            this.address = address;
            this.tel = tel;
            this.mobile = mobile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewCompanySellerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewCompanySellerResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddNewCompanySellerResponseBody Body;
        
        public AddNewCompanySellerResponse() {
        }
        
        public AddNewCompanySellerResponse(AllPayWebServiceTest.AllPaysharedws.AddNewCompanySellerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewCompanySellerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddNewCompanySellerResult;
        
        public AddNewCompanySellerResponseBody() {
        }
        
        public AddNewCompanySellerResponseBody(string AddNewCompanySellerResult) {
            this.AddNewCompanySellerResult = AddNewCompanySellerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewMerchantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewMerchant", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddNewMerchantRequestBody Body;
        
        public AddNewMerchantRequest() {
        }
        
        public AddNewMerchantRequest(AllPayWebServiceTest.AllPaysharedws.AddNewMerchantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewMerchantRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int otp_esc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long allpayMID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string corpname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string corpid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string comboss;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string bossid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string webname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string contact;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string tel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int charge;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public int bank;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public int isAE;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public int isUnionPay;
        
        public AddNewMerchantRequestBody() {
        }
        
        public AddNewMerchantRequestBody(int otp_esc, long allpayMID, string corpname, string corpid, string comboss, string bossid, string webname, string contact, string address, string tel, string mobile, int charge, int bank, int isAE, int isUnionPay) {
            this.otp_esc = otp_esc;
            this.allpayMID = allpayMID;
            this.corpname = corpname;
            this.corpid = corpid;
            this.comboss = comboss;
            this.bossid = bossid;
            this.webname = webname;
            this.contact = contact;
            this.address = address;
            this.tel = tel;
            this.mobile = mobile;
            this.charge = charge;
            this.bank = bank;
            this.isAE = isAE;
            this.isUnionPay = isUnionPay;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewMerchantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewMerchantResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddNewMerchantResponseBody Body;
        
        public AddNewMerchantResponse() {
        }
        
        public AddNewMerchantResponse(AllPayWebServiceTest.AllPaysharedws.AddNewMerchantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewMerchantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddNewMerchantResult;
        
        public AddNewMerchantResponseBody() {
        }
        
        public AddNewMerchantResponseBody(string AddNewMerchantResult) {
            this.AddNewMerchantResult = AddNewMerchantResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateNewMerchantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateNewMerchant", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.UpdateNewMerchantRequestBody Body;
        
        public UpdateNewMerchantRequest() {
        }
        
        public UpdateNewMerchantRequest(AllPayWebServiceTest.AllPaysharedws.UpdateNewMerchantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateNewMerchantRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int otp_esc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string corpname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string corpid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string comboss;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string bossid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string webname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string contact;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string tel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int charge;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int allpayto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public int nosale;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public long gid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public long allpayMID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string rentRate;
        
        public UpdateNewMerchantRequestBody() {
        }
        
        public UpdateNewMerchantRequestBody(
                    int otp_esc, 
                    string corpname, 
                    string corpid, 
                    string comboss, 
                    string bossid, 
                    string webname, 
                    string contact, 
                    string address, 
                    string tel, 
                    string mobile, 
                    int charge, 
                    int allpayto, 
                    int nosale, 
                    long gid, 
                    long allpayMID, 
                    string rentRate) {
            this.otp_esc = otp_esc;
            this.corpname = corpname;
            this.corpid = corpid;
            this.comboss = comboss;
            this.bossid = bossid;
            this.webname = webname;
            this.contact = contact;
            this.address = address;
            this.tel = tel;
            this.mobile = mobile;
            this.charge = charge;
            this.allpayto = allpayto;
            this.nosale = nosale;
            this.gid = gid;
            this.allpayMID = allpayMID;
            this.rentRate = rentRate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateNewMerchantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateNewMerchantResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.UpdateNewMerchantResponseBody Body;
        
        public UpdateNewMerchantResponse() {
        }
        
        public UpdateNewMerchantResponse(AllPayWebServiceTest.AllPaysharedws.UpdateNewMerchantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateNewMerchantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateNewMerchantResult;
        
        public UpdateNewMerchantResponseBody() {
        }
        
        public UpdateNewMerchantResponseBody(string UpdateNewMerchantResult) {
            this.UpdateNewMerchantResult = UpdateNewMerchantResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewCompanyMerchantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewCompanyMerchant", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddNewCompanyMerchantRequestBody Body;
        
        public AddNewCompanyMerchantRequest() {
        }
        
        public AddNewCompanyMerchantRequest(AllPayWebServiceTest.AllPaysharedws.AddNewCompanyMerchantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddNewCompanyMerchantRequestBody {
        
        public AddNewCompanyMerchantRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewCompanyMerchantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewCompanyMerchantResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddNewCompanyMerchantResponseBody Body;
        
        public AddNewCompanyMerchantResponse() {
        }
        
        public AddNewCompanyMerchantResponse(AllPayWebServiceTest.AllPaysharedws.AddNewCompanyMerchantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewCompanyMerchantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddNewCompanyMerchantResult;
        
        public AddNewCompanyMerchantResponseBody() {
        }
        
        public AddNewCompanyMerchantResponseBody(string AddNewCompanyMerchantResult) {
            this.AddNewCompanyMerchantResult = AddNewCompanyMerchantResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNotifyMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNotifyMessage", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageRequestBody Body;
        
        public AddNotifyMessageRequest() {
        }
        
        public AddNotifyMessageRequest(AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNotifyMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long mid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string body;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int webSiteID;
        
        public AddNotifyMessageRequestBody() {
        }
        
        public AddNotifyMessageRequestBody(long mid, string subject, string body, int webSiteID) {
            this.mid = mid;
            this.subject = subject;
            this.body = body;
            this.webSiteID = webSiteID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNotifyMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNotifyMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageResponseBody Body;
        
        public AddNotifyMessageResponse() {
        }
        
        public AddNotifyMessageResponse(AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNotifyMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddNotifyMessageResult;
        
        public AddNotifyMessageResponseBody() {
        }
        
        public AddNotifyMessageResponseBody(int AddNotifyMessageResult) {
            this.AddNotifyMessageResult = AddNotifyMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNotifyMessageAndPushRssByCustomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNotifyMessageAndPushRssByCustom", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageAndPushRssByCustomRequestBody Body;
        
        public AddNotifyMessageAndPushRssByCustomRequest() {
        }
        
        public AddNotifyMessageAndPushRssByCustomRequest(AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageAndPushRssByCustomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNotifyMessageAndPushRssByCustomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long mid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string body;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int webSiteID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string appPushSubject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string appPushTitle;
        
        public AddNotifyMessageAndPushRssByCustomRequestBody() {
        }
        
        public AddNotifyMessageAndPushRssByCustomRequestBody(long mid, string subject, string body, int webSiteID, string appPushSubject, string appPushTitle) {
            this.mid = mid;
            this.subject = subject;
            this.body = body;
            this.webSiteID = webSiteID;
            this.appPushSubject = appPushSubject;
            this.appPushTitle = appPushTitle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNotifyMessageAndPushRssByCustomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNotifyMessageAndPushRssByCustomResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageAndPushRssByCustomResponseBody Body;
        
        public AddNotifyMessageAndPushRssByCustomResponse() {
        }
        
        public AddNotifyMessageAndPushRssByCustomResponse(AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageAndPushRssByCustomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNotifyMessageAndPushRssByCustomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddNotifyMessageAndPushRssByCustomResult;
        
        public AddNotifyMessageAndPushRssByCustomResponseBody() {
        }
        
        public AddNotifyMessageAndPushRssByCustomResponseBody(int AddNotifyMessageAndPushRssByCustomResult) {
            this.AddNotifyMessageAndPushRssByCustomResult = AddNotifyMessageAndPushRssByCustomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewMerchantForRentDeviceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewMerchantForRentDevice", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddNewMerchantForRentDeviceRequestBody Body;
        
        public AddNewMerchantForRentDeviceRequest() {
        }
        
        public AddNewMerchantForRentDeviceRequest(AllPayWebServiceTest.AllPaysharedws.AddNewMerchantForRentDeviceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewMerchantForRentDeviceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int otp_esc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long allpayMID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string corpname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string corpid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string comboss;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string bossid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string webname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string contact;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string tel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int charge;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public int bank;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public int isAE;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public int isUnionPay;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public int isAutoClose;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string rentRate;
        
        public AddNewMerchantForRentDeviceRequestBody() {
        }
        
        public AddNewMerchantForRentDeviceRequestBody(
                    int otp_esc, 
                    long allpayMID, 
                    string corpname, 
                    string corpid, 
                    string comboss, 
                    string bossid, 
                    string webname, 
                    string contact, 
                    string address, 
                    string tel, 
                    string mobile, 
                    int charge, 
                    int bank, 
                    int isAE, 
                    int isUnionPay, 
                    int isAutoClose, 
                    string rentRate) {
            this.otp_esc = otp_esc;
            this.allpayMID = allpayMID;
            this.corpname = corpname;
            this.corpid = corpid;
            this.comboss = comboss;
            this.bossid = bossid;
            this.webname = webname;
            this.contact = contact;
            this.address = address;
            this.tel = tel;
            this.mobile = mobile;
            this.charge = charge;
            this.bank = bank;
            this.isAE = isAE;
            this.isUnionPay = isUnionPay;
            this.isAutoClose = isAutoClose;
            this.rentRate = rentRate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewMerchantForRentDeviceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewMerchantForRentDeviceResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AddNewMerchantForRentDeviceResponseBody Body;
        
        public AddNewMerchantForRentDeviceResponse() {
        }
        
        public AddNewMerchantForRentDeviceResponse(AllPayWebServiceTest.AllPaysharedws.AddNewMerchantForRentDeviceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewMerchantForRentDeviceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddNewMerchantForRentDeviceResult;
        
        public AddNewMerchantForRentDeviceResponseBody() {
        }
        
        public AddNewMerchantForRentDeviceResponseBody(string AddNewMerchantForRentDeviceResult) {
            this.AddNewMerchantForRentDeviceResult = AddNewMerchantForRentDeviceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AES_EnCryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AES_EnCrypt", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AES_EnCryptRequestBody Body;
        
        public AES_EnCryptRequest() {
        }
        
        public AES_EnCryptRequest(AllPayWebServiceTest.AllPaysharedws.AES_EnCryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AES_EnCryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sIV;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EncodeString;
        
        public AES_EnCryptRequestBody() {
        }
        
        public AES_EnCryptRequestBody(string sKey, string sIV, string sData, string EncodeString) {
            this.sKey = sKey;
            this.sIV = sIV;
            this.sData = sData;
            this.EncodeString = EncodeString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AES_EnCryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AES_EnCryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AES_EnCryptResponseBody Body;
        
        public AES_EnCryptResponse() {
        }
        
        public AES_EnCryptResponse(AllPayWebServiceTest.AllPaysharedws.AES_EnCryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AES_EnCryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AES_EnCryptResult;
        
        public AES_EnCryptResponseBody() {
        }
        
        public AES_EnCryptResponseBody(string AES_EnCryptResult) {
            this.AES_EnCryptResult = AES_EnCryptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AES_DeCryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AES_DeCrypt", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AES_DeCryptRequestBody Body;
        
        public AES_DeCryptRequest() {
        }
        
        public AES_DeCryptRequest(AllPayWebServiceTest.AllPaysharedws.AES_DeCryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AES_DeCryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sIV;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EncodeString;
        
        public AES_DeCryptRequestBody() {
        }
        
        public AES_DeCryptRequestBody(string sKey, string sIV, string sData, string EncodeString) {
            this.sKey = sKey;
            this.sIV = sIV;
            this.sData = sData;
            this.EncodeString = EncodeString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AES_DeCryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AES_DeCryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.AES_DeCryptResponseBody Body;
        
        public AES_DeCryptResponse() {
        }
        
        public AES_DeCryptResponse(AllPayWebServiceTest.AllPaysharedws.AES_DeCryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AES_DeCryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AES_DeCryptResult;
        
        public AES_DeCryptResponseBody() {
        }
        
        public AES_DeCryptResponseBody(string AES_DeCryptResult) {
            this.AES_DeCryptResult = AES_DeCryptResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AllPaySharedWSSoapChannel : AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AllPaySharedWSSoapClient : System.ServiceModel.ClientBase<AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap>, AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap {
        
        public AllPaySharedWSSoapClient() {
        }
        
        public AllPaySharedWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AllPaySharedWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllPaySharedWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllPaySharedWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.AllPaysharedws.SendSMSResponse AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap.SendSMS(AllPayWebServiceTest.AllPaysharedws.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public string SendSMS(string Phone, string MsgData, int SmsType) {
            AllPayWebServiceTest.AllPaysharedws.SendSMSRequest inValue = new AllPayWebServiceTest.AllPaysharedws.SendSMSRequest();
            inValue.Body = new AllPayWebServiceTest.AllPaysharedws.SendSMSRequestBody();
            inValue.Body.Phone = Phone;
            inValue.Body.MsgData = MsgData;
            inValue.Body.SmsType = SmsType;
            AllPayWebServiceTest.AllPaysharedws.SendSMSResponse retVal = ((AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap)(this)).SendSMS(inValue);
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.AllPaysharedws.AddFastMemberResponse AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap.AddFastMember(AllPayWebServiceTest.AllPaysharedws.AddFastMemberRequest request) {
            return base.Channel.AddFastMember(request);
        }
        
        public long AddFastMember(long tradeID, string tradeNo, string cName, string cellPhone, string email, int addMember) {
            AllPayWebServiceTest.AllPaysharedws.AddFastMemberRequest inValue = new AllPayWebServiceTest.AllPaysharedws.AddFastMemberRequest();
            inValue.Body = new AllPayWebServiceTest.AllPaysharedws.AddFastMemberRequestBody();
            inValue.Body.tradeID = tradeID;
            inValue.Body.tradeNo = tradeNo;
            inValue.Body.cName = cName;
            inValue.Body.cellPhone = cellPhone;
            inValue.Body.email = email;
            inValue.Body.addMember = addMember;
            AllPayWebServiceTest.AllPaysharedws.AddFastMemberResponse retVal = ((AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap)(this)).AddFastMember(inValue);
            return retVal.Body.AddFastMemberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.AllPaysharedws.AddBonusMemberResponse AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap.AddBonusMember(AllPayWebServiceTest.AllPaysharedws.AddBonusMemberRequest request) {
            return base.Channel.AddBonusMember(request);
        }
        
        public AllPayWebServiceTest.AllPaysharedws.ApiReturnModel AddBonusMember(string cName, string IDNO, string cellPhone, string email, string CompanyID, string Birthday, string CompanyName) {
            AllPayWebServiceTest.AllPaysharedws.AddBonusMemberRequest inValue = new AllPayWebServiceTest.AllPaysharedws.AddBonusMemberRequest();
            inValue.Body = new AllPayWebServiceTest.AllPaysharedws.AddBonusMemberRequestBody();
            inValue.Body.cName = cName;
            inValue.Body.IDNO = IDNO;
            inValue.Body.cellPhone = cellPhone;
            inValue.Body.email = email;
            inValue.Body.CompanyID = CompanyID;
            inValue.Body.Birthday = Birthday;
            inValue.Body.CompanyName = CompanyName;
            AllPayWebServiceTest.AllPaysharedws.AddBonusMemberResponse retVal = ((AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap)(this)).AddBonusMember(inValue);
            return retVal.Body.AddBonusMemberResult;
        }
        
        public int GetUnreadNotifyMessageCount(long mid, int webSiteID) {
            return base.Channel.GetUnreadNotifyMessageCount(mid, webSiteID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.AllPaysharedws.AddNewPersonalSellerResponse AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap.AddNewPersonalSeller(AllPayWebServiceTest.AllPaysharedws.AddNewPersonalSellerRequest request) {
            return base.Channel.AddNewPersonalSeller(request);
        }
        
        public string AddNewPersonalSeller(int otp_esc, long allpayMID, string corpname, string comboss, string bossid, string webname, string contact, string address, string tel, string mobile) {
            AllPayWebServiceTest.AllPaysharedws.AddNewPersonalSellerRequest inValue = new AllPayWebServiceTest.AllPaysharedws.AddNewPersonalSellerRequest();
            inValue.Body = new AllPayWebServiceTest.AllPaysharedws.AddNewPersonalSellerRequestBody();
            inValue.Body.otp_esc = otp_esc;
            inValue.Body.allpayMID = allpayMID;
            inValue.Body.corpname = corpname;
            inValue.Body.comboss = comboss;
            inValue.Body.bossid = bossid;
            inValue.Body.webname = webname;
            inValue.Body.contact = contact;
            inValue.Body.address = address;
            inValue.Body.tel = tel;
            inValue.Body.mobile = mobile;
            AllPayWebServiceTest.AllPaysharedws.AddNewPersonalSellerResponse retVal = ((AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap)(this)).AddNewPersonalSeller(inValue);
            return retVal.Body.AddNewPersonalSellerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.AllPaysharedws.AddNewCompanySellerResponse AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap.AddNewCompanySeller(AllPayWebServiceTest.AllPaysharedws.AddNewCompanySellerRequest request) {
            return base.Channel.AddNewCompanySeller(request);
        }
        
        public string AddNewCompanySeller(int otp_esc, long allpayMID, string corpname, string corpid, string comboss, string bossid, string webname, string contact, string address, string tel, string mobile) {
            AllPayWebServiceTest.AllPaysharedws.AddNewCompanySellerRequest inValue = new AllPayWebServiceTest.AllPaysharedws.AddNewCompanySellerRequest();
            inValue.Body = new AllPayWebServiceTest.AllPaysharedws.AddNewCompanySellerRequestBody();
            inValue.Body.otp_esc = otp_esc;
            inValue.Body.allpayMID = allpayMID;
            inValue.Body.corpname = corpname;
            inValue.Body.corpid = corpid;
            inValue.Body.comboss = comboss;
            inValue.Body.bossid = bossid;
            inValue.Body.webname = webname;
            inValue.Body.contact = contact;
            inValue.Body.address = address;
            inValue.Body.tel = tel;
            inValue.Body.mobile = mobile;
            AllPayWebServiceTest.AllPaysharedws.AddNewCompanySellerResponse retVal = ((AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap)(this)).AddNewCompanySeller(inValue);
            return retVal.Body.AddNewCompanySellerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.AllPaysharedws.AddNewMerchantResponse AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap.AddNewMerchant(AllPayWebServiceTest.AllPaysharedws.AddNewMerchantRequest request) {
            return base.Channel.AddNewMerchant(request);
        }
        
        public string AddNewMerchant(int otp_esc, long allpayMID, string corpname, string corpid, string comboss, string bossid, string webname, string contact, string address, string tel, string mobile, int charge, int bank, int isAE, int isUnionPay) {
            AllPayWebServiceTest.AllPaysharedws.AddNewMerchantRequest inValue = new AllPayWebServiceTest.AllPaysharedws.AddNewMerchantRequest();
            inValue.Body = new AllPayWebServiceTest.AllPaysharedws.AddNewMerchantRequestBody();
            inValue.Body.otp_esc = otp_esc;
            inValue.Body.allpayMID = allpayMID;
            inValue.Body.corpname = corpname;
            inValue.Body.corpid = corpid;
            inValue.Body.comboss = comboss;
            inValue.Body.bossid = bossid;
            inValue.Body.webname = webname;
            inValue.Body.contact = contact;
            inValue.Body.address = address;
            inValue.Body.tel = tel;
            inValue.Body.mobile = mobile;
            inValue.Body.charge = charge;
            inValue.Body.bank = bank;
            inValue.Body.isAE = isAE;
            inValue.Body.isUnionPay = isUnionPay;
            AllPayWebServiceTest.AllPaysharedws.AddNewMerchantResponse retVal = ((AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap)(this)).AddNewMerchant(inValue);
            return retVal.Body.AddNewMerchantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.AllPaysharedws.UpdateNewMerchantResponse AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap.UpdateNewMerchant(AllPayWebServiceTest.AllPaysharedws.UpdateNewMerchantRequest request) {
            return base.Channel.UpdateNewMerchant(request);
        }
        
        public string UpdateNewMerchant(
                    int otp_esc, 
                    string corpname, 
                    string corpid, 
                    string comboss, 
                    string bossid, 
                    string webname, 
                    string contact, 
                    string address, 
                    string tel, 
                    string mobile, 
                    int charge, 
                    int allpayto, 
                    int nosale, 
                    long gid, 
                    long allpayMID, 
                    string rentRate) {
            AllPayWebServiceTest.AllPaysharedws.UpdateNewMerchantRequest inValue = new AllPayWebServiceTest.AllPaysharedws.UpdateNewMerchantRequest();
            inValue.Body = new AllPayWebServiceTest.AllPaysharedws.UpdateNewMerchantRequestBody();
            inValue.Body.otp_esc = otp_esc;
            inValue.Body.corpname = corpname;
            inValue.Body.corpid = corpid;
            inValue.Body.comboss = comboss;
            inValue.Body.bossid = bossid;
            inValue.Body.webname = webname;
            inValue.Body.contact = contact;
            inValue.Body.address = address;
            inValue.Body.tel = tel;
            inValue.Body.mobile = mobile;
            inValue.Body.charge = charge;
            inValue.Body.allpayto = allpayto;
            inValue.Body.nosale = nosale;
            inValue.Body.gid = gid;
            inValue.Body.allpayMID = allpayMID;
            inValue.Body.rentRate = rentRate;
            AllPayWebServiceTest.AllPaysharedws.UpdateNewMerchantResponse retVal = ((AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap)(this)).UpdateNewMerchant(inValue);
            return retVal.Body.UpdateNewMerchantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.AllPaysharedws.AddNewCompanyMerchantResponse AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap.AddNewCompanyMerchant(AllPayWebServiceTest.AllPaysharedws.AddNewCompanyMerchantRequest request) {
            return base.Channel.AddNewCompanyMerchant(request);
        }
        
        public string AddNewCompanyMerchant() {
            AllPayWebServiceTest.AllPaysharedws.AddNewCompanyMerchantRequest inValue = new AllPayWebServiceTest.AllPaysharedws.AddNewCompanyMerchantRequest();
            inValue.Body = new AllPayWebServiceTest.AllPaysharedws.AddNewCompanyMerchantRequestBody();
            AllPayWebServiceTest.AllPaysharedws.AddNewCompanyMerchantResponse retVal = ((AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap)(this)).AddNewCompanyMerchant(inValue);
            return retVal.Body.AddNewCompanyMerchantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageResponse AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap.AddNotifyMessage(AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageRequest request) {
            return base.Channel.AddNotifyMessage(request);
        }
        
        public int AddNotifyMessage(long mid, string subject, string body, int webSiteID) {
            AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageRequest inValue = new AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageRequest();
            inValue.Body = new AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageRequestBody();
            inValue.Body.mid = mid;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            inValue.Body.webSiteID = webSiteID;
            AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageResponse retVal = ((AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap)(this)).AddNotifyMessage(inValue);
            return retVal.Body.AddNotifyMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageAndPushRssByCustomResponse AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap.AddNotifyMessageAndPushRssByCustom(AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageAndPushRssByCustomRequest request) {
            return base.Channel.AddNotifyMessageAndPushRssByCustom(request);
        }
        
        public int AddNotifyMessageAndPushRssByCustom(long mid, string subject, string body, int webSiteID, string appPushSubject, string appPushTitle) {
            AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageAndPushRssByCustomRequest inValue = new AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageAndPushRssByCustomRequest();
            inValue.Body = new AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageAndPushRssByCustomRequestBody();
            inValue.Body.mid = mid;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            inValue.Body.webSiteID = webSiteID;
            inValue.Body.appPushSubject = appPushSubject;
            inValue.Body.appPushTitle = appPushTitle;
            AllPayWebServiceTest.AllPaysharedws.AddNotifyMessageAndPushRssByCustomResponse retVal = ((AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap)(this)).AddNotifyMessageAndPushRssByCustom(inValue);
            return retVal.Body.AddNotifyMessageAndPushRssByCustomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.AllPaysharedws.AddNewMerchantForRentDeviceResponse AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap.AddNewMerchantForRentDevice(AllPayWebServiceTest.AllPaysharedws.AddNewMerchantForRentDeviceRequest request) {
            return base.Channel.AddNewMerchantForRentDevice(request);
        }
        
        public string AddNewMerchantForRentDevice(
                    int otp_esc, 
                    long allpayMID, 
                    string corpname, 
                    string corpid, 
                    string comboss, 
                    string bossid, 
                    string webname, 
                    string contact, 
                    string address, 
                    string tel, 
                    string mobile, 
                    int charge, 
                    int bank, 
                    int isAE, 
                    int isUnionPay, 
                    int isAutoClose, 
                    string rentRate) {
            AllPayWebServiceTest.AllPaysharedws.AddNewMerchantForRentDeviceRequest inValue = new AllPayWebServiceTest.AllPaysharedws.AddNewMerchantForRentDeviceRequest();
            inValue.Body = new AllPayWebServiceTest.AllPaysharedws.AddNewMerchantForRentDeviceRequestBody();
            inValue.Body.otp_esc = otp_esc;
            inValue.Body.allpayMID = allpayMID;
            inValue.Body.corpname = corpname;
            inValue.Body.corpid = corpid;
            inValue.Body.comboss = comboss;
            inValue.Body.bossid = bossid;
            inValue.Body.webname = webname;
            inValue.Body.contact = contact;
            inValue.Body.address = address;
            inValue.Body.tel = tel;
            inValue.Body.mobile = mobile;
            inValue.Body.charge = charge;
            inValue.Body.bank = bank;
            inValue.Body.isAE = isAE;
            inValue.Body.isUnionPay = isUnionPay;
            inValue.Body.isAutoClose = isAutoClose;
            inValue.Body.rentRate = rentRate;
            AllPayWebServiceTest.AllPaysharedws.AddNewMerchantForRentDeviceResponse retVal = ((AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap)(this)).AddNewMerchantForRentDevice(inValue);
            return retVal.Body.AddNewMerchantForRentDeviceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.AllPaysharedws.AES_EnCryptResponse AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap.AES_EnCrypt(AllPayWebServiceTest.AllPaysharedws.AES_EnCryptRequest request) {
            return base.Channel.AES_EnCrypt(request);
        }
        
        public string AES_EnCrypt(string sKey, string sIV, string sData, string EncodeString) {
            AllPayWebServiceTest.AllPaysharedws.AES_EnCryptRequest inValue = new AllPayWebServiceTest.AllPaysharedws.AES_EnCryptRequest();
            inValue.Body = new AllPayWebServiceTest.AllPaysharedws.AES_EnCryptRequestBody();
            inValue.Body.sKey = sKey;
            inValue.Body.sIV = sIV;
            inValue.Body.sData = sData;
            inValue.Body.EncodeString = EncodeString;
            AllPayWebServiceTest.AllPaysharedws.AES_EnCryptResponse retVal = ((AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap)(this)).AES_EnCrypt(inValue);
            return retVal.Body.AES_EnCryptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.AllPaysharedws.AES_DeCryptResponse AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap.AES_DeCrypt(AllPayWebServiceTest.AllPaysharedws.AES_DeCryptRequest request) {
            return base.Channel.AES_DeCrypt(request);
        }
        
        public string AES_DeCrypt(string sKey, string sIV, string sData, string EncodeString) {
            AllPayWebServiceTest.AllPaysharedws.AES_DeCryptRequest inValue = new AllPayWebServiceTest.AllPaysharedws.AES_DeCryptRequest();
            inValue.Body = new AllPayWebServiceTest.AllPaysharedws.AES_DeCryptRequestBody();
            inValue.Body.sKey = sKey;
            inValue.Body.sIV = sIV;
            inValue.Body.sData = sData;
            inValue.Body.EncodeString = EncodeString;
            AllPayWebServiceTest.AllPaysharedws.AES_DeCryptResponse retVal = ((AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap)(this)).AES_DeCrypt(inValue);
            return retVal.Body.AES_DeCryptResult;
        }
    }
}
