//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.269
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllPayWebServiceTest.AllPaysharedws {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AllPaysharedws.AllPaySharedWSSoap")]
    public interface AllPaySharedWSSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的項目名稱  Phone 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        AllPayWebServiceTest.AllPaysharedws.SendSMSResponse SendSMS(AllPayWebServiceTest.AllPaysharedws.SendSMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(AllPayWebServiceTest.AllPaysharedws.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MsgData;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int SmsType;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(string Phone, string MsgData, int SmsType) {
            this.Phone = Phone;
            this.MsgData = MsgData;
            this.SmsType = SmsType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public AllPayWebServiceTest.AllPaysharedws.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(AllPayWebServiceTest.AllPaysharedws.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSResult;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(string SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AllPaySharedWSSoapChannel : AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AllPaySharedWSSoapClient : System.ServiceModel.ClientBase<AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap>, AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap {
        
        public AllPaySharedWSSoapClient() {
        }
        
        public AllPaySharedWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AllPaySharedWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllPaySharedWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllPaySharedWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.AllPaysharedws.SendSMSResponse AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap.SendSMS(AllPayWebServiceTest.AllPaysharedws.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public string SendSMS(string Phone, string MsgData, int SmsType) {
            AllPayWebServiceTest.AllPaysharedws.SendSMSRequest inValue = new AllPayWebServiceTest.AllPaysharedws.SendSMSRequest();
            inValue.Body = new AllPayWebServiceTest.AllPaysharedws.SendSMSRequestBody();
            inValue.Body.Phone = Phone;
            inValue.Body.MsgData = MsgData;
            inValue.Body.SmsType = SmsType;
            AllPayWebServiceTest.AllPaysharedws.SendSMSResponse retVal = ((AllPayWebServiceTest.AllPaysharedws.AllPaySharedWSSoap)(this)).SendSMS(inValue);
            return retVal.Body.SendSMSResult;
        }
    }
}
