//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllPayWebServiceTest.ApiWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentMerchantFunction", Namespace="http://testApiService.allpay.com.tw/")]
    [System.SerializableAttribute()]
    public partial class PaymentMerchantFunction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long MIDField;
        
        private short PaymentTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentSubTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentSubTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashIVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AllowedIPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long MID {
            get {
                return this.MIDField;
            }
            set {
                if ((this.MIDField.Equals(value) != true)) {
                    this.MIDField = value;
                    this.RaisePropertyChanged("MID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short PaymentTypeID {
            get {
                return this.PaymentTypeIDField;
            }
            set {
                if ((this.PaymentTypeIDField.Equals(value) != true)) {
                    this.PaymentTypeIDField = value;
                    this.RaisePropertyChanged("PaymentTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PaymentSubTypeID {
            get {
                return this.PaymentSubTypeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentSubTypeIDField, value) != true)) {
                    this.PaymentSubTypeIDField = value;
                    this.RaisePropertyChanged("PaymentSubTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PaymentSubTypeName {
            get {
                return this.PaymentSubTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentSubTypeNameField, value) != true)) {
                    this.PaymentSubTypeNameField = value;
                    this.RaisePropertyChanged("PaymentSubTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string States {
            get {
                return this.StatesField;
            }
            set {
                if ((object.ReferenceEquals(this.StatesField, value) != true)) {
                    this.StatesField = value;
                    this.RaisePropertyChanged("States");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string HashKey {
            get {
                return this.HashKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.HashKeyField, value) != true)) {
                    this.HashKeyField = value;
                    this.RaisePropertyChanged("HashKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string HashIV {
            get {
                return this.HashIVField;
            }
            set {
                if ((object.ReferenceEquals(this.HashIVField, value) != true)) {
                    this.HashIVField = value;
                    this.RaisePropertyChanged("HashIV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string AllowedIP {
            get {
                return this.AllowedIPField;
            }
            set {
                if ((object.ReferenceEquals(this.AllowedIPField, value) != true)) {
                    this.AllowedIPField = value;
                    this.RaisePropertyChanged("AllowedIP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AllPayMerchantFunction", Namespace="http://testApiService.allpay.com.tw/")]
    [System.SerializableAttribute()]
    public partial class AllPayMerchantFunction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long MIDField;
        
        private short PaymentTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentSubTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentSubTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashIVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AllowedIPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long MID {
            get {
                return this.MIDField;
            }
            set {
                if ((this.MIDField.Equals(value) != true)) {
                    this.MIDField = value;
                    this.RaisePropertyChanged("MID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short PaymentTypeID {
            get {
                return this.PaymentTypeIDField;
            }
            set {
                if ((this.PaymentTypeIDField.Equals(value) != true)) {
                    this.PaymentTypeIDField = value;
                    this.RaisePropertyChanged("PaymentTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PaymentSubTypeID {
            get {
                return this.PaymentSubTypeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentSubTypeIDField, value) != true)) {
                    this.PaymentSubTypeIDField = value;
                    this.RaisePropertyChanged("PaymentSubTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PaymentSubTypeName {
            get {
                return this.PaymentSubTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentSubTypeNameField, value) != true)) {
                    this.PaymentSubTypeNameField = value;
                    this.RaisePropertyChanged("PaymentSubTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string States {
            get {
                return this.StatesField;
            }
            set {
                if ((object.ReferenceEquals(this.StatesField, value) != true)) {
                    this.StatesField = value;
                    this.RaisePropertyChanged("States");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string HashKey {
            get {
                return this.HashKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.HashKeyField, value) != true)) {
                    this.HashKeyField = value;
                    this.RaisePropertyChanged("HashKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string HashIV {
            get {
                return this.HashIVField;
            }
            set {
                if ((object.ReferenceEquals(this.HashIVField, value) != true)) {
                    this.HashIVField = value;
                    this.RaisePropertyChanged("HashIV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string AllowedIP {
            get {
                return this.AllowedIPField;
            }
            set {
                if ((object.ReferenceEquals(this.AllowedIPField, value) != true)) {
                    this.AllowedIPField = value;
                    this.RaisePropertyChanged("AllowedIP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://testApiService.allpay.com.tw/", ConfigurationName="ApiWS.ApiWSSoap")]
    public interface ApiWSSoap {
        
        // CODEGEN: 命名空間 http://testApiService.allpay.com.tw/ 的元素名稱  paymentTypeName 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://testApiService.allpay.com.tw/GetPaymentMerchantFunction", ReplyAction="*")]
        AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionResponse GetPaymentMerchantFunction(AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionRequest request);
        
        // CODEGEN: 命名空間 http://testApiService.allpay.com.tw/ 的元素名稱  paymentTypeName 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://testApiService.allpay.com.tw/GetPaymentMerchantFunctionByBankName", ReplyAction="*")]
        AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByBankNameResponse GetPaymentMerchantFunctionByBankName(AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByBankNameRequest request);
        
        // CODEGEN: 命名空間 http://testApiService.allpay.com.tw/ 的元素名稱  GetPaymentMerchantFunctionByMIDResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://testApiService.allpay.com.tw/GetPaymentMerchantFunctionByMID", ReplyAction="*")]
        AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByMIDResponse GetPaymentMerchantFunctionByMID(AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByMIDRequest request);
        
        // CODEGEN: 命名空間 http://testApiService.allpay.com.tw/ 的元素名稱  paymentName 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://testApiService.allpay.com.tw/GetPaymentMerchantAllowedIPByMID", ReplyAction="*")]
        AllPayWebServiceTest.ApiWS.GetPaymentMerchantAllowedIPByMIDResponse GetPaymentMerchantAllowedIPByMID(AllPayWebServiceTest.ApiWS.GetPaymentMerchantAllowedIPByMIDRequest request);
        
        // CODEGEN: 命名空間 http://testApiService.allpay.com.tw/ 的元素名稱  GetAllPayMerchantFunctionByMerchantResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://testApiService.allpay.com.tw/GetAllPayMerchantFunctionByMerchant", ReplyAction="*")]
        AllPayWebServiceTest.ApiWS.GetAllPayMerchantFunctionByMerchantResponse GetAllPayMerchantFunctionByMerchant(AllPayWebServiceTest.ApiWS.GetAllPayMerchantFunctionByMerchantRequest request);
        
        // CODEGEN: 命名空間 http://testApiService.allpay.com.tw/ 的元素名稱  UserCode 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://testApiService.allpay.com.tw/CheckUserCodeUnique", ReplyAction="*")]
        AllPayWebServiceTest.ApiWS.CheckUserCodeUniqueResponse CheckUserCodeUnique(AllPayWebServiceTest.ApiWS.CheckUserCodeUniqueRequest request);
        
        // CODEGEN: 命名空間 http://testApiService.allpay.com.tw/ 的元素名稱  sData 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://testApiService.allpay.com.tw/EnCrypt", ReplyAction="*")]
        AllPayWebServiceTest.ApiWS.EnCryptResponse EnCrypt(AllPayWebServiceTest.ApiWS.EnCryptRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPaymentMerchantFunctionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPaymentMerchantFunction", Namespace="http://testApiService.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionRequestBody Body;
        
        public GetPaymentMerchantFunctionRequest() {
        }
        
        public GetPaymentMerchantFunctionRequest(AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://testApiService.allpay.com.tw/")]
    public partial class GetPaymentMerchantFunctionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long mid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string paymentTypeName;
        
        public GetPaymentMerchantFunctionRequestBody() {
        }
        
        public GetPaymentMerchantFunctionRequestBody(long mid, string paymentTypeName) {
            this.mid = mid;
            this.paymentTypeName = paymentTypeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPaymentMerchantFunctionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPaymentMerchantFunctionResponse", Namespace="http://testApiService.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionResponseBody Body;
        
        public GetPaymentMerchantFunctionResponse() {
        }
        
        public GetPaymentMerchantFunctionResponse(AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://testApiService.allpay.com.tw/")]
    public partial class GetPaymentMerchantFunctionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AllPayWebServiceTest.ApiWS.PaymentMerchantFunction GetPaymentMerchantFunctionResult;
        
        public GetPaymentMerchantFunctionResponseBody() {
        }
        
        public GetPaymentMerchantFunctionResponseBody(AllPayWebServiceTest.ApiWS.PaymentMerchantFunction GetPaymentMerchantFunctionResult) {
            this.GetPaymentMerchantFunctionResult = GetPaymentMerchantFunctionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPaymentMerchantFunctionByBankNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPaymentMerchantFunctionByBankName", Namespace="http://testApiService.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByBankNameRequestBody Body;
        
        public GetPaymentMerchantFunctionByBankNameRequest() {
        }
        
        public GetPaymentMerchantFunctionByBankNameRequest(AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByBankNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://testApiService.allpay.com.tw/")]
    public partial class GetPaymentMerchantFunctionByBankNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long mid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string paymentTypeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string bankName;
        
        public GetPaymentMerchantFunctionByBankNameRequestBody() {
        }
        
        public GetPaymentMerchantFunctionByBankNameRequestBody(long mid, string paymentTypeName, string bankName) {
            this.mid = mid;
            this.paymentTypeName = paymentTypeName;
            this.bankName = bankName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPaymentMerchantFunctionByBankNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPaymentMerchantFunctionByBankNameResponse", Namespace="http://testApiService.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByBankNameResponseBody Body;
        
        public GetPaymentMerchantFunctionByBankNameResponse() {
        }
        
        public GetPaymentMerchantFunctionByBankNameResponse(AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByBankNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://testApiService.allpay.com.tw/")]
    public partial class GetPaymentMerchantFunctionByBankNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AllPayWebServiceTest.ApiWS.PaymentMerchantFunction GetPaymentMerchantFunctionByBankNameResult;
        
        public GetPaymentMerchantFunctionByBankNameResponseBody() {
        }
        
        public GetPaymentMerchantFunctionByBankNameResponseBody(AllPayWebServiceTest.ApiWS.PaymentMerchantFunction GetPaymentMerchantFunctionByBankNameResult) {
            this.GetPaymentMerchantFunctionByBankNameResult = GetPaymentMerchantFunctionByBankNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPaymentMerchantFunctionByMIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPaymentMerchantFunctionByMID", Namespace="http://testApiService.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByMIDRequestBody Body;
        
        public GetPaymentMerchantFunctionByMIDRequest() {
        }
        
        public GetPaymentMerchantFunctionByMIDRequest(AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByMIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://testApiService.allpay.com.tw/")]
    public partial class GetPaymentMerchantFunctionByMIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long mid;
        
        public GetPaymentMerchantFunctionByMIDRequestBody() {
        }
        
        public GetPaymentMerchantFunctionByMIDRequestBody(long mid) {
            this.mid = mid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPaymentMerchantFunctionByMIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPaymentMerchantFunctionByMIDResponse", Namespace="http://testApiService.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByMIDResponseBody Body;
        
        public GetPaymentMerchantFunctionByMIDResponse() {
        }
        
        public GetPaymentMerchantFunctionByMIDResponse(AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByMIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://testApiService.allpay.com.tw/")]
    public partial class GetPaymentMerchantFunctionByMIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AllPayWebServiceTest.ApiWS.PaymentMerchantFunction GetPaymentMerchantFunctionByMIDResult;
        
        public GetPaymentMerchantFunctionByMIDResponseBody() {
        }
        
        public GetPaymentMerchantFunctionByMIDResponseBody(AllPayWebServiceTest.ApiWS.PaymentMerchantFunction GetPaymentMerchantFunctionByMIDResult) {
            this.GetPaymentMerchantFunctionByMIDResult = GetPaymentMerchantFunctionByMIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPaymentMerchantAllowedIPByMIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPaymentMerchantAllowedIPByMID", Namespace="http://testApiService.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ApiWS.GetPaymentMerchantAllowedIPByMIDRequestBody Body;
        
        public GetPaymentMerchantAllowedIPByMIDRequest() {
        }
        
        public GetPaymentMerchantAllowedIPByMIDRequest(AllPayWebServiceTest.ApiWS.GetPaymentMerchantAllowedIPByMIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://testApiService.allpay.com.tw/")]
    public partial class GetPaymentMerchantAllowedIPByMIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long mid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int functionType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string paymentName;
        
        public GetPaymentMerchantAllowedIPByMIDRequestBody() {
        }
        
        public GetPaymentMerchantAllowedIPByMIDRequestBody(long mid, int functionType, string paymentName) {
            this.mid = mid;
            this.functionType = functionType;
            this.paymentName = paymentName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPaymentMerchantAllowedIPByMIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPaymentMerchantAllowedIPByMIDResponse", Namespace="http://testApiService.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ApiWS.GetPaymentMerchantAllowedIPByMIDResponseBody Body;
        
        public GetPaymentMerchantAllowedIPByMIDResponse() {
        }
        
        public GetPaymentMerchantAllowedIPByMIDResponse(AllPayWebServiceTest.ApiWS.GetPaymentMerchantAllowedIPByMIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://testApiService.allpay.com.tw/")]
    public partial class GetPaymentMerchantAllowedIPByMIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPaymentMerchantAllowedIPByMIDResult;
        
        public GetPaymentMerchantAllowedIPByMIDResponseBody() {
        }
        
        public GetPaymentMerchantAllowedIPByMIDResponseBody(string GetPaymentMerchantAllowedIPByMIDResult) {
            this.GetPaymentMerchantAllowedIPByMIDResult = GetPaymentMerchantAllowedIPByMIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPayMerchantFunctionByMerchantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPayMerchantFunctionByMerchant", Namespace="http://testApiService.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ApiWS.GetAllPayMerchantFunctionByMerchantRequestBody Body;
        
        public GetAllPayMerchantFunctionByMerchantRequest() {
        }
        
        public GetAllPayMerchantFunctionByMerchantRequest(AllPayWebServiceTest.ApiWS.GetAllPayMerchantFunctionByMerchantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://testApiService.allpay.com.tw/")]
    public partial class GetAllPayMerchantFunctionByMerchantRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long mid;
        
        public GetAllPayMerchantFunctionByMerchantRequestBody() {
        }
        
        public GetAllPayMerchantFunctionByMerchantRequestBody(long mid) {
            this.mid = mid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPayMerchantFunctionByMerchantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPayMerchantFunctionByMerchantResponse", Namespace="http://testApiService.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ApiWS.GetAllPayMerchantFunctionByMerchantResponseBody Body;
        
        public GetAllPayMerchantFunctionByMerchantResponse() {
        }
        
        public GetAllPayMerchantFunctionByMerchantResponse(AllPayWebServiceTest.ApiWS.GetAllPayMerchantFunctionByMerchantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://testApiService.allpay.com.tw/")]
    public partial class GetAllPayMerchantFunctionByMerchantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AllPayWebServiceTest.ApiWS.AllPayMerchantFunction GetAllPayMerchantFunctionByMerchantResult;
        
        public GetAllPayMerchantFunctionByMerchantResponseBody() {
        }
        
        public GetAllPayMerchantFunctionByMerchantResponseBody(AllPayWebServiceTest.ApiWS.AllPayMerchantFunction GetAllPayMerchantFunctionByMerchantResult) {
            this.GetAllPayMerchantFunctionByMerchantResult = GetAllPayMerchantFunctionByMerchantResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserCodeUniqueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserCodeUnique", Namespace="http://testApiService.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ApiWS.CheckUserCodeUniqueRequestBody Body;
        
        public CheckUserCodeUniqueRequest() {
        }
        
        public CheckUserCodeUniqueRequest(AllPayWebServiceTest.ApiWS.CheckUserCodeUniqueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://testApiService.allpay.com.tw/")]
    public partial class CheckUserCodeUniqueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeUserCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long mid;
        
        public CheckUserCodeUniqueRequestBody() {
        }
        
        public CheckUserCodeUniqueRequestBody(string UserCode, string DeUserCode, long mid) {
            this.UserCode = UserCode;
            this.DeUserCode = DeUserCode;
            this.mid = mid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserCodeUniqueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserCodeUniqueResponse", Namespace="http://testApiService.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ApiWS.CheckUserCodeUniqueResponseBody Body;
        
        public CheckUserCodeUniqueResponse() {
        }
        
        public CheckUserCodeUniqueResponse(AllPayWebServiceTest.ApiWS.CheckUserCodeUniqueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://testApiService.allpay.com.tw/")]
    public partial class CheckUserCodeUniqueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckUserCodeUniqueResult;
        
        public CheckUserCodeUniqueResponseBody() {
        }
        
        public CheckUserCodeUniqueResponseBody(bool CheckUserCodeUniqueResult) {
            this.CheckUserCodeUniqueResult = CheckUserCodeUniqueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnCryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnCrypt", Namespace="http://testApiService.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ApiWS.EnCryptRequestBody Body;
        
        public EnCryptRequest() {
        }
        
        public EnCryptRequest(AllPayWebServiceTest.ApiWS.EnCryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://testApiService.allpay.com.tw/")]
    public partial class EnCryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sData;
        
        public EnCryptRequestBody() {
        }
        
        public EnCryptRequestBody(string sData) {
            this.sData = sData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnCryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnCryptResponse", Namespace="http://testApiService.allpay.com.tw/", Order=0)]
        public AllPayWebServiceTest.ApiWS.EnCryptResponseBody Body;
        
        public EnCryptResponse() {
        }
        
        public EnCryptResponse(AllPayWebServiceTest.ApiWS.EnCryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://testApiService.allpay.com.tw/")]
    public partial class EnCryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnCryptResult;
        
        public EnCryptResponseBody() {
        }
        
        public EnCryptResponseBody(string EnCryptResult) {
            this.EnCryptResult = EnCryptResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApiWSSoapChannel : AllPayWebServiceTest.ApiWS.ApiWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiWSSoapClient : System.ServiceModel.ClientBase<AllPayWebServiceTest.ApiWS.ApiWSSoap>, AllPayWebServiceTest.ApiWS.ApiWSSoap {
        
        public ApiWSSoapClient() {
        }
        
        public ApiWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionResponse AllPayWebServiceTest.ApiWS.ApiWSSoap.GetPaymentMerchantFunction(AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionRequest request) {
            return base.Channel.GetPaymentMerchantFunction(request);
        }
        
        public AllPayWebServiceTest.ApiWS.PaymentMerchantFunction GetPaymentMerchantFunction(long mid, string paymentTypeName) {
            AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionRequest inValue = new AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionRequest();
            inValue.Body = new AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionRequestBody();
            inValue.Body.mid = mid;
            inValue.Body.paymentTypeName = paymentTypeName;
            AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionResponse retVal = ((AllPayWebServiceTest.ApiWS.ApiWSSoap)(this)).GetPaymentMerchantFunction(inValue);
            return retVal.Body.GetPaymentMerchantFunctionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByBankNameResponse AllPayWebServiceTest.ApiWS.ApiWSSoap.GetPaymentMerchantFunctionByBankName(AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByBankNameRequest request) {
            return base.Channel.GetPaymentMerchantFunctionByBankName(request);
        }
        
        public AllPayWebServiceTest.ApiWS.PaymentMerchantFunction GetPaymentMerchantFunctionByBankName(long mid, string paymentTypeName, string bankName) {
            AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByBankNameRequest inValue = new AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByBankNameRequest();
            inValue.Body = new AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByBankNameRequestBody();
            inValue.Body.mid = mid;
            inValue.Body.paymentTypeName = paymentTypeName;
            inValue.Body.bankName = bankName;
            AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByBankNameResponse retVal = ((AllPayWebServiceTest.ApiWS.ApiWSSoap)(this)).GetPaymentMerchantFunctionByBankName(inValue);
            return retVal.Body.GetPaymentMerchantFunctionByBankNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByMIDResponse AllPayWebServiceTest.ApiWS.ApiWSSoap.GetPaymentMerchantFunctionByMID(AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByMIDRequest request) {
            return base.Channel.GetPaymentMerchantFunctionByMID(request);
        }
        
        public AllPayWebServiceTest.ApiWS.PaymentMerchantFunction GetPaymentMerchantFunctionByMID(long mid) {
            AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByMIDRequest inValue = new AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByMIDRequest();
            inValue.Body = new AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByMIDRequestBody();
            inValue.Body.mid = mid;
            AllPayWebServiceTest.ApiWS.GetPaymentMerchantFunctionByMIDResponse retVal = ((AllPayWebServiceTest.ApiWS.ApiWSSoap)(this)).GetPaymentMerchantFunctionByMID(inValue);
            return retVal.Body.GetPaymentMerchantFunctionByMIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.ApiWS.GetPaymentMerchantAllowedIPByMIDResponse AllPayWebServiceTest.ApiWS.ApiWSSoap.GetPaymentMerchantAllowedIPByMID(AllPayWebServiceTest.ApiWS.GetPaymentMerchantAllowedIPByMIDRequest request) {
            return base.Channel.GetPaymentMerchantAllowedIPByMID(request);
        }
        
        public string GetPaymentMerchantAllowedIPByMID(long mid, int functionType, string paymentName) {
            AllPayWebServiceTest.ApiWS.GetPaymentMerchantAllowedIPByMIDRequest inValue = new AllPayWebServiceTest.ApiWS.GetPaymentMerchantAllowedIPByMIDRequest();
            inValue.Body = new AllPayWebServiceTest.ApiWS.GetPaymentMerchantAllowedIPByMIDRequestBody();
            inValue.Body.mid = mid;
            inValue.Body.functionType = functionType;
            inValue.Body.paymentName = paymentName;
            AllPayWebServiceTest.ApiWS.GetPaymentMerchantAllowedIPByMIDResponse retVal = ((AllPayWebServiceTest.ApiWS.ApiWSSoap)(this)).GetPaymentMerchantAllowedIPByMID(inValue);
            return retVal.Body.GetPaymentMerchantAllowedIPByMIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.ApiWS.GetAllPayMerchantFunctionByMerchantResponse AllPayWebServiceTest.ApiWS.ApiWSSoap.GetAllPayMerchantFunctionByMerchant(AllPayWebServiceTest.ApiWS.GetAllPayMerchantFunctionByMerchantRequest request) {
            return base.Channel.GetAllPayMerchantFunctionByMerchant(request);
        }
        
        public AllPayWebServiceTest.ApiWS.AllPayMerchantFunction GetAllPayMerchantFunctionByMerchant(long mid) {
            AllPayWebServiceTest.ApiWS.GetAllPayMerchantFunctionByMerchantRequest inValue = new AllPayWebServiceTest.ApiWS.GetAllPayMerchantFunctionByMerchantRequest();
            inValue.Body = new AllPayWebServiceTest.ApiWS.GetAllPayMerchantFunctionByMerchantRequestBody();
            inValue.Body.mid = mid;
            AllPayWebServiceTest.ApiWS.GetAllPayMerchantFunctionByMerchantResponse retVal = ((AllPayWebServiceTest.ApiWS.ApiWSSoap)(this)).GetAllPayMerchantFunctionByMerchant(inValue);
            return retVal.Body.GetAllPayMerchantFunctionByMerchantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.ApiWS.CheckUserCodeUniqueResponse AllPayWebServiceTest.ApiWS.ApiWSSoap.CheckUserCodeUnique(AllPayWebServiceTest.ApiWS.CheckUserCodeUniqueRequest request) {
            return base.Channel.CheckUserCodeUnique(request);
        }
        
        public bool CheckUserCodeUnique(string UserCode, string DeUserCode, long mid) {
            AllPayWebServiceTest.ApiWS.CheckUserCodeUniqueRequest inValue = new AllPayWebServiceTest.ApiWS.CheckUserCodeUniqueRequest();
            inValue.Body = new AllPayWebServiceTest.ApiWS.CheckUserCodeUniqueRequestBody();
            inValue.Body.UserCode = UserCode;
            inValue.Body.DeUserCode = DeUserCode;
            inValue.Body.mid = mid;
            AllPayWebServiceTest.ApiWS.CheckUserCodeUniqueResponse retVal = ((AllPayWebServiceTest.ApiWS.ApiWSSoap)(this)).CheckUserCodeUnique(inValue);
            return retVal.Body.CheckUserCodeUniqueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllPayWebServiceTest.ApiWS.EnCryptResponse AllPayWebServiceTest.ApiWS.ApiWSSoap.EnCrypt(AllPayWebServiceTest.ApiWS.EnCryptRequest request) {
            return base.Channel.EnCrypt(request);
        }
        
        public string EnCrypt(string sData) {
            AllPayWebServiceTest.ApiWS.EnCryptRequest inValue = new AllPayWebServiceTest.ApiWS.EnCryptRequest();
            inValue.Body = new AllPayWebServiceTest.ApiWS.EnCryptRequestBody();
            inValue.Body.sData = sData;
            AllPayWebServiceTest.ApiWS.EnCryptResponse retVal = ((AllPayWebServiceTest.ApiWS.ApiWSSoap)(this)).EnCrypt(inValue);
            return retVal.Body.EnCryptResult;
        }
    }
}
